### ISSUE TITLE
double report

### ISSUE THREAD

**Issue by lgarren** [LArSoft/cms-bot#27]
I notice that when I trigger a build with more than one PR, the results are reported twice in the originating PR.  See https://github.com/LArSoft/larsim/pull/90 for an example.  This is a minor annoyance.

**Comment by vitodb** [comment]
One message is posted by the Jenkins CI job, it prepares a properties file to trigger the Jenkins project GithubIntegration/post-to-github-pr that is posting the message.

By looking at GithubIntegration/post-to-github-pr logs, I see it has been activated twice by the larsim PR, this seems to be happening because the "PULL_REQUESTS" parameter has the larsim PR listed twice.
I think this is due to the way the CI collects PRs, there are occasions, as this one, where some PRs are listed twice.
I'll try to update the CI code to prevent this to happen.
